### ISSUE TITLE
失效了

### ISSUE THREAD

**Issue by goodjack** [yurenju/ptt-redirect#6]
現在看 Disp.cc 不會自己轉址 QQ

**Comment by shouko** [comment]
他們是不是把原文連結拿掉了 QQ
覺得惡劣

**Comment by goodjack** [comment]
看起來只是 manifest.json 沒有設定到啦 #8

**Comment by goodjack** [comment]
Closed by 8bb597b43374636b15b3a2245e5f90d1817ff6cd
